# This is a Terraform Workflow

name: Terraform Init Build CI

on:
  workflow_call:
    inputs:
      destroy:
        description: 'True to destroy all the infraestructure'
        required: false
        type: boolean

jobs:
  preperingEnv:
    outputs:
      branch: ${{steps.extract_branch.outputs.branch}}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" >> $GITHUB_OUTPUT
          echo Se recibe variable destroy: ${{ inputs.destroy }}
        id: extract_branch
  
  
  terraformPlan:
    if:  ${{ !inputs.destroy }}
    runs-on: ubuntu-latest
    needs: preperingEnv
    steps:
      - uses: actions/checkout@v3
      - name: echo Terraform Plan
        run: echo Hello, world!
      - name: Terraform Plan
        run: |
          pwd
          ls -l
          echo Trabajando con la rama en Plan: ${{ needs.preperingEnv.outputs.branch }}
          echo GITHUB_REF: ${GITHUB_REF}
          echo GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}
          
          
  terraformVerify:
    needs: [preperingEnv,terraformPlan]
    if:  ${{ !inputs.destroy }}
    environment:
        name: approvers
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Verify
        run: echo "Step Terraform Verify"
      - name: Multiline
        run: |
          pwd
          ls -l
          echo Trabajando con la rama en Plan: ${{ needs.preperingEnv.outputs.branch }}
          
          
  TerraformDestroy:
    if:  ${{ inputs.destroy }}
    needs: preperingEnv
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Destroy
        run: echo "Terraform Destroy"
      - name: Multiline
        run: |
          echo Trabajando con la rama en Plan: ${{ needs.preperingEnv.outputs.branch }}
